/* ========================================
   Output JS — 아웃풋 뷰어 페이지 로직
   파일 목록 + 콘텐츠 뷰어 + 복사/다운로드
   ======================================== */

'use strict';

/* CC BY 4.0 라이선스 전문 — ZIP 다운로드 시 포함 */
const LICENSE_CONTENT = `Creative Commons Attribution 4.0 International (CC BY 4.0)

Copyright (c) ${new Date().getFullYear()} GospelFix

You are free to:
  Share — copy and redistribute the material in any medium or format
  Adapt — remix, transform, and build upon the material for any purpose, even commercially.

Under the following terms:
  Attribution — You must give appropriate credit, provide a link to the license,
  and indicate if changes were made.

License details: https://creativecommons.org/licenses/by/4.0/

---
Generated by GospelFix · https://gospelfix.github.io/profile/
`;

let agentsData = [];
let historyData = [];
let outputsData = [];
let activeOutputId = null;

/* ─── 초기화 ─── */
const init = async () => {
  try {
    /* 모든 에이전시 파일을 병렬 로드 후 중복 없이 병합 */
    const [allAgentFiles, history, outputs] = await Promise.all([
      Promise.all([
        fetchJSON('../data/agents.json').then(d => d.agents),
        fetchJSON('../data/marketing-agents.json').then(d => d.agents).catch(() => []),
        fetchJSON('../data/design-agents.json').then(d => d.agents).catch(() => []),
        fetchJSON('../data/dev-agents.json').then(d => d.agents).catch(() => []),
      ]),
      fetchJSON('../data/history.json').then(d => d.runs),
      fetchJSON('../data/outputs.json').then(d => d.outputs),
    ]);

    /* id 기준 중복 제거 병합 */
    const agentMap = new Map();
    allAgentFiles.flat().forEach(a => agentMap.set(a.id, a));
    agentsData  = Array.from(agentMap.values());
    historyData = history;
    outputsData = outputs;

    /* localStorage에 저장된 이전 생성 결과물 앞에 병합 */
    const stored = Store.get();
    if (stored.generatedRuns?.length)    historyData = [...stored.generatedRuns,    ...historyData];
    if (stored.generatedOutputs?.length) outputsData = [...stored.generatedOutputs, ...outputsData];

    renderFilePanel();

    /* URL 파라미터로 초기 선택 결정 */
    const params = new URLSearchParams(window.location.search);
    const outputParam = params.get('output');
    const runParam = params.get('run');

    if (outputParam) {
      selectOutput(outputParam);
    } else if (runParam) {
      /* 특정 런의 첫 번째 아웃풋 선택 */
      const firstOutput = outputsData.find(o => o.runId === runParam);
      if (firstOutput) selectOutput(firstOutput.id);
      else renderEmptyViewer();
    } else {
      /* 기본: 가장 최신 아웃풋 선택 */
      const latest = outputsData[0];
      if (latest) selectOutput(latest.id);
      else renderEmptyViewer();
    }
  } catch (e) {
    console.error('아웃풋 데이터 로드 실패:', e);
    renderEmptyViewer();
  }
};

/** JSON fetch 헬퍼 */
const fetchJSON = async (url) => {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`fetch 실패: ${url}`);
  return res.json();
};

/* ─── 파일 목록 패널 렌더링 ─── */
const renderFilePanel = () => {
  const container = document.getElementById('file-panel-body');
  if (!container) return;

  /* 실행 별로 그룹핑 */
  const grouped = {};
  outputsData.forEach(output => {
    if (!grouped[output.runId]) grouped[output.runId] = [];
    grouped[output.runId].push(output);
  });

  /* 내림차순: 최신 실행이 위에 표시 */
  const groupsHTML = historyData.map(run => {
    const runOutputs = grouped[run.id];
    if (!runOutputs || !runOutputs.length) return '';

    const itemsHTML = runOutputs.map(output => {
      /* run 스냅샷 우선 조회 — 실행 당시 직급이 정확히 표시됨 */
      const agentSnapshot = run.agentsSnapshot?.find(a => a.id === output.agentId);
      const agent = agentSnapshot || agentsData.find(a => a.id === output.agentId);
      if (!agent) return '';

      const isActive = output.id === activeOutputId;

      return `
        <div class="file-item${isActive ? ' active' : ''}" data-output-id="${output.id}"
             role="button" tabindex="0" aria-label="${output.label} 열기">
          <div class="file-item-icon">${agent.icon}</div>
          <div class="file-item-info">
            <div class="file-item-name" style="color:var(${agent.accentVar})">📄 ${output.fileName}</div>
            <div class="file-item-meta">${agent.name} · ${agent.rank}</div>
          </div>
          <div class="file-item-dot" style="background:var(${agent.accentVar})"></div>
        </div>
      `;
    }).join('');

    return `
      <div class="run-group">
        <div class="run-group-header">
          <div class="run-group-label">${run.label}</div>
          <button class="zip-btn" data-run-id="${run.id}" aria-label="${run.label} 전체 ZIP 다운로드">
            ⬇ ZIP
          </button>
        </div>
        ${itemsHTML}
      </div>
    `;
  }).join('');

  container.innerHTML = groupsHTML || '<div style="text-align:center;color:var(--text-dim);font-size:11px;padding:20px">파일 없음</div>';

  /* 파일 항목 이벤트 */
  container.querySelectorAll('.file-item[data-output-id]').forEach(item => {
    item.addEventListener('click', () => selectOutput(item.dataset.outputId));
    item.addEventListener('keydown', (e) => {
      if (e.key === 'Enter' || e.key === ' ') selectOutput(item.dataset.outputId);
    });
  });

  /* ZIP 다운로드 버튼 이벤트 */
  container.querySelectorAll('.zip-btn[data-run-id]').forEach(btn => {
    btn.addEventListener('click', () => downloadRunZip(btn.dataset.runId, btn));
  });
};

/** 아웃풋 선택 → 뷰어 업데이트 */
const selectOutput = (outputId) => {
  activeOutputId = outputId;
  renderFilePanel(); // 선택 표시 갱신
  renderContentViewer(outputId);

  /* Store에 선택 상태 저장 */
  Store.set({ selectedOutputId: outputId });
};

/* ─── 콘텐츠 뷰어 렌더링 ─── */
const renderContentViewer = (outputId) => {
  const viewer = document.getElementById('content-viewer');
  if (!viewer) return;

  const output = outputsData.find(o => o.id === outputId);
  if (!output) {
    renderEmptyViewer();
    return;
  }

  const run = historyData.find(r => r.id === output.runId);
  /* run 스냅샷 우선 조회 — 실행 당시 직급이 정확히 표시됨 */
  const agentSnapshot = run?.agentsSnapshot?.find(a => a.id === output.agentId);
  const agent = agentSnapshot || agentsData.find(a => a.id === output.agentId);
  if (!agent || !run) return;

  const createdAt = formatDate(output.createdAt);

  viewer.innerHTML = `
    <div class="viewer-header">
      <div>
        <div class="viewer-title">
          <span>${agent.icon}</span>
          <span style="color:var(${agent.accentVar})">${output.label}</span>
          <span class="rank-badge" style="background:var(${agent.glowVar});color:var(${agent.accentVar})">${agent.rank}</span>
        </div>
        <div class="viewer-meta">${run.label} · ${createdAt}</div>
      </div>
      <div class="viewer-actions">
        <button class="btn btn-ghost btn-sm copy-btn" id="copy-btn" aria-label="내용 복사">
          📋 복사
        </button>
        <button class="btn btn-ghost btn-sm" id="download-btn" aria-label="파일 다운로드">
          ⬇️ 다운로드
        </button>
      </div>
    </div>
    <div class="viewer-body">
      <pre class="content-text" id="content-text">${escapeHTML(buildFrontmatter(output, agent) + output.content)}</pre>
    </div>
  `;

  /* 복사 버튼 */
  document.getElementById('copy-btn').addEventListener('click', () => copyContent(output.content));

  /* 다운로드 버튼 */
  document.getElementById('download-btn').addEventListener('click', () => downloadContent(output));
};

/** 빈 뷰어 */
const renderEmptyViewer = () => {
  const viewer = document.getElementById('content-viewer');
  if (!viewer) return;

  viewer.innerHTML = `
    <div class="viewer-empty">
      <div class="viewer-empty-icon">📄</div>
      <div class="viewer-empty-text">
        좌측에서 파일을 선택하면<br>내용이 표시됩니다
      </div>
    </div>
  `;
};

/* ─── 복사 ─── */
const copyContent = async (text) => {
  const btn = document.getElementById('copy-btn');
  try {
    await navigator.clipboard.writeText(text);
    if (btn) {
      btn.textContent = '✓ 복사됨';
      btn.classList.add('copied');
      setTimeout(() => {
        btn.textContent = '📋 복사';
        btn.classList.remove('copied');
      }, 2000);
    }
  } catch {
    /* clipboard API 미지원 시 fallback */
    const el = document.createElement('textarea');
    el.value = text;
    el.style.position = 'fixed';
    el.style.opacity = '0';
    document.body.appendChild(el);
    el.select();
    document.execCommand('copy');
    document.body.removeChild(el);
    if (btn) {
      btn.textContent = '✓ 복사됨';
      setTimeout(() => { btn.textContent = '📋 복사'; }, 2000);
    }
  }
};

/* ─── 다운로드 ─── */
const downloadContent = (output) => {
  const agent = agentsData.find(a => a.id === output.agentId);
  const content = agent
    ? buildFrontmatter(output, agent) + output.content
    : output.content;
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${output.fileName}_${output.runId}.md`;
  link.style.display = 'none';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  /* 메모리 해제 */
  setTimeout(() => URL.revokeObjectURL(url), 1000);
};

/* ─── 실행 그룹 전체 ZIP 다운로드 ─── */
const downloadRunZip = async (runId, btnEl) => {
  const run = historyData.find(r => r.id === runId);
  const runOutputs = outputsData.filter(o => o.runId === runId);
  if (!run || !runOutputs.length) return;

  /* 버튼 로딩 상태 */
  if (btnEl) {
    btnEl.disabled = true;
    btnEl.textContent = '⏳';
  }

  try {
    const zip = new JSZip();
    /* ZIP 내부 폴더명: run.id는 항상 alphanumeric+hyphen 형식 보장 */
    const folderName = runId.replace(/^run-/, 'skill-');
    const folder = zip.folder(folderName);

    runOutputs.forEach(output => {
      const agent = agentsData.find(a => a.id === output.agentId);
      const content = agent
        ? buildFrontmatter(output, agent) + output.content
        : output.content;
      folder.file(`${output.fileName}.md`, content);
    });

    /* SKILL.md 및 LICENSE.txt 생성 후 최상위 폴더에 포함 */
    folder.file('SKILL.md', buildSkillMd(run, runOutputs));
    folder.file('LICENSE.txt', LICENSE_CONTENT);

    const blob = await zip.generateAsync({ type: 'blob' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${folderName}.zip`;
    link.style.display = 'none';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    setTimeout(() => URL.revokeObjectURL(url), 1000);
  } finally {
    if (btnEl) {
      btnEl.disabled = false;
      btnEl.textContent = '⬇ ZIP';
    }
  }
};

/** YAML 프론트매터 문자열 생성 */
const buildFrontmatter = (output, agent) => {
  return [
    '---',
    `name: ${output.fileName}`,
    `label: ${output.label}`,
    `agent: ${output.agentId}`,
    `description: ${agent.desc}`,
    `model: ${agent.model}`,
    '---',
    '',
  ].join('\n');
};

/** ZIP에 포함될 SKILL.md 인덱스 파일 생성 */
const buildSkillMd = (run, runOutputs) => {
  const skillEntries = runOutputs.map(output => {
    const agent = agentsData.find(a => a.id === output.agentId);
    return [
      `### ${output.fileName}`,
      '',
      '```yaml',
      `name: ${output.fileName}`,
      `label: ${output.label}`,
      `agent: ${output.agentId}`,
      `description: ${agent ? agent.desc : output.label}`,
      `model: ${agent ? agent.model : ''}`,
      `file: ${output.fileName}.md`,
      '```',
    ].join('\n');
  }).join('\n\n');

  /* run.id = 'run-001' 또는 'run-1741510000000' → skill- 접두사로 변환 */
  const pkgName = run.id.replace(/^run-/, 'skill-');
  const today = new Date().toISOString().split('T')[0];

  return [
    '---',
    `name: ${pkgName}`,
    `description: ${run.label} 파이프라인 실행 결과물 패키지`,
    `generated: ${today}`,
    '---',
    '',
    `# SKILL.md — ${run.label}`,
    '',
    '> 이 파일은 자동 생성된 스킬 인덱스입니다.',
    '',
    '---',
    '',
    '## Skills',
    '',
    skillEntries,
  ].join('\n');
};

/** HTML 이스케이프 (XSS 방지) */
const escapeHTML = (str) => {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
};

/** 날짜 포맷 */
const formatDate = (isoString) => {
  const d = new Date(isoString);
  return `${d.getFullYear()}.${String(d.getMonth() + 1).padStart(2, '0')}.${String(d.getDate()).padStart(2, '0')} ${String(d.getHours()).padStart(2, '0')}:${String(d.getMinutes()).padStart(2, '0')}`;
};

/* ─── DOM 준비 후 초기화 ─── */
document.addEventListener('DOMContentLoaded', init);
